/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Opportunities;
import model.Organization;
import services.OpportunitiesService;

/**
 *
 * @author kanimbajustine
 */
public class VolunteersFrame extends javax.swing.JFrame {

    DefaultTableModel tableModel = new DefaultTableModel();
    /**
     * Creates new form VolunteersFrame
     */
    public VolunteersFrame() {
        initComponents();
        addColumns();
        retrieveOpps();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        volTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        searchTxt = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Volunteers Hub");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(292, 292, 292)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        volTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        volTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                volTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(volTable);

        jLabel2.setText("Search By Location:");

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(365, 365, 365)
                .addComponent(jLabel2)
                .addGap(31, 31, 31)
                .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(searchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchBtn))
                .addGap(13, 13, 13))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        if(searchTxt.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(this,
                    "Please input a search keyword!",
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        try{
            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 8000);
            OpportunitiesService oppSrv = (OpportunitiesService)reg.lookup("opportunities");
            Opportunities oppObj = new Opportunities();
            oppObj.setOppLocation(searchTxt.getText());
            List<Opportunities> oppList = oppSrv.searchByLocation(oppObj);
            tableModel = new DefaultTableModel();
            addColumns();
            for(Opportunities opp : oppList){
                tableModel.addRow(new Object[]{
                    opp.getOppId(),
                    opp.getOppTitle(),
                    opp.getOppDescription(),
                    opp.getOppSkills(),
                    opp.getOppLocation(),
                    opp.getOppSlots(),
                    opp.getOppStartDate(),
                    opp.getOppEndDate(),
                    opp.getOrganization().getOrgId()
                });
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void volTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_volTableMouseClicked
        int selectedRowIndex = volTable.getSelectedRow();
       
        Opportunities opp = new Opportunities();
        opp.setOppId(Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 0).toString()));
        opp.setOppTitle(tableModel.getValueAt(selectedRowIndex, 1).toString());
        opp.setOppDescription(tableModel.getValueAt(selectedRowIndex, 2).toString());
        opp.setOppSkills(tableModel.getValueAt(selectedRowIndex, 3).toString());
        opp.setOppLocation(tableModel.getValueAt(selectedRowIndex, 4).toString());
        opp.setOppSlots(Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 5).toString()));
        opp.setOppStartDate((Date)tableModel.getValueAt(selectedRowIndex, 6));
        opp.setOppEndDate((Date)tableModel.getValueAt(selectedRowIndex, 7));
        int orgId = Integer.parseInt(tableModel.getValueAt(selectedRowIndex, 8).toString());
        
        OppDetails oppDet = new OppDetails(opp, orgId);
        oppDet.setVisible(true);
        dispose();
    }//GEN-LAST:event_volTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VolunteersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VolunteersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VolunteersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VolunteersFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VolunteersFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTxt;
    private javax.swing.JTable volTable;
    // End of variables declaration//GEN-END:variables

    private void addColumns() {
        tableModel.addColumn("Id");
        tableModel.addColumn("Title");
        tableModel.addColumn("Description");
        tableModel.addColumn("Skills Required");
        tableModel.addColumn("Location");
        tableModel.addColumn("Slots Available");
        tableModel.addColumn("Start Date");
        tableModel.addColumn("End Date");
        tableModel.addColumn("Organization");
        
        volTable.setModel(tableModel);
    }

    private void retrieveOpps() {
        try{
            Registry reg = LocateRegistry.getRegistry("127.0.0.1", 8000);
            OpportunitiesService oppSrv = (OpportunitiesService)reg.lookup("opportunities");
            List<Opportunities> oppList = oppSrv.viewOpps();
            for(Opportunities opp : oppList){
                tableModel.addRow(new Object[]{
                    opp.getOppId(),
                    opp.getOppTitle(),
                    opp.getOppDescription(),
                    opp.getOppSkills(),
                    opp.getOppLocation(),
                    opp.getOppSlots(),
                    opp.getOppStartDate(),
                    opp.getOppEndDate(),
                    opp.getOrganization().getOrgId()
                });
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    
    
}
